require("test_helpers")
print("--- test_area ---")

test("area.new creates area", function()
    local a = lv.area.new()
    expect_true(a ~= nil)
end)

test("area getters return numbers", function()
    local a = lv.area.new()
    expect_type(lv.area.get_x1(a), "number", "x1")
    expect_type(lv.area.get_x2(a), "number", "x2")
    expect_type(lv.area.get_y1(a), "number", "y1")
    expect_type(lv.area.get_y2(a), "number", "y2")
end)

test("area from obj.get_coords", function()
    local obj = lv.obj.new(window)
    lv.obj.set_pos(obj, 10, 20)
    lv.obj.set_size(obj, 50, 30)
    test_tick(1)
    local a = lv.area.new()
    lv.obj.get_coords(obj, a)
    local x1 = lv.area.get_x1(a)
    local y1 = lv.area.get_y1(a)
    expect_type(x1, "number", "x1 type")
    expect_type(y1, "number", "y1 type")
    lv.obj.del(obj)
end)
