require("test_helpers")
print("--- test_arc ---")

test("arc.new creates arc", function()
    local a = lv.arc.new(window)
    expect_true(a ~= nil)
    lv.obj.del(a)
end)

test("arc.set_angles", function()
    local a = lv.arc.new(window)
    lv.arc.set_angles(a, 0, 270)
    expect_true(true)
    lv.obj.del(a)
end)

test("arc.set_rotation", function()
    local a = lv.arc.new(window)
    lv.arc.set_rotation(a, 90)
    expect_true(true)
    lv.obj.del(a)
end)

test("arc with style", function()
    local a = lv.arc.new(window)
    local s = lv.style.new()
    lv.style.set_arc_color(s, lv.color.hex(0x00FF00))
    lv.style.set_arc_width(s, 8)
    lv.obj.add_style(a, s, lv.PART_INDICATOR)
    expect_true(true)
    lv.obj.del(a)
end)
