require("test_helpers")
print("--- test_group ---")

test("group.add_obj / remove_obj", function()
    local obj = lv.obj.new(window)
    lv.group.add_obj(document, obj)
    lv.group.remove_obj(obj)
    expect_true(true)
    lv.obj.del(obj)
end)

test("group.focus_obj", function()
    local obj = lv.obj.new(window)
    lv.obj.add_flag(obj, lv.OBJ_FLAG_CLICKABLE)
    lv.group.add_obj(document, obj)
    lv.group.focus_obj(obj)
    expect_true(true)
    lv.group.remove_obj(obj)
    lv.obj.del(obj)
end)

test("group.set_editing", function()
    lv.group.set_editing(document, true)
    lv.group.set_editing(document, false)
    expect_true(true)
end)

test("group.set_wrap", function()
    lv.group.set_wrap(document, true)
    lv.group.set_wrap(document, false)
    expect_true(true)
end)

test("btn.new auto-added to default group", function()
    -- document is set as default group in test runner
    lv.group.remove_all_objs(document)
    local btn = lv.btn.new(window)
    -- btn should be auto-added to default group
    -- verify by focusing it (would fail if not in group)
    lv.group.focus_obj(btn)
    -- send FOCUSED event and check it arrives
    local focused = false
    lv.obj.add_event_cb(btn, function() focused = true end, lv.EVENT_FOCUSED)
    lv.event.send(btn, lv.EVENT_FOCUSED)
    expect_true(focused, "btn should be focusable in default group")
    lv.group.remove_all_objs(document)
    lv.obj.del(btn)
end)

test("group.remove_all_objs", function()
    local o1 = lv.obj.new(window)
    local o2 = lv.obj.new(window)
    lv.group.add_obj(document, o1)
    lv.group.add_obj(document, o2)
    lv.group.remove_all_objs(document)
    expect_true(true)
    lv.obj.del(o1)
    lv.obj.del(o2)
end)
