require("test_helpers")
print("--- test_label ---")

test("label.new creates label", function()
    local lbl = lv.label.new(window)
    expect_true(lbl ~= nil)
    lv.obj.del(lbl)
end)

test("label.set_text / get_text", function()
    local lbl = lv.label.new(window)
    lv.label.set_text(lbl, "Hello World")
    expect_eq(lv.label.get_text(lbl), "Hello World", "text")
    lv.obj.del(lbl)
end)

test("label.set_text with accented chars", function()
    local lbl = lv.label.new(window)
    lv.label.set_text(lbl, "Crée ton personnage")
    expect_eq(lv.label.get_text(lbl), "Crée ton personnage", "accented text")
    lv.obj.del(lbl)
end)

test("label.set_long_mode", function()
    local lbl = lv.label.new(window)
    lv.label.set_long_mode(lbl, lv.LABEL_LONG_WRAP)
    lv.label.set_long_mode(lbl, lv.LABEL_LONG_DOT)
    lv.label.set_long_mode(lbl, lv.LABEL_LONG_CLIP)
    expect_true(true)
    lv.obj.del(lbl)
end)

test("label with font style", function()
    local lbl = lv.label.new(window)
    lv.label.set_text(lbl, "Test")
    lv.obj.set_style_text_font(lbl, lv.font.nunito_extrabold_20)
    lv.obj.set_style_text_color(lbl, lv.color.white())
    test_tick(1)
    expect_true(true)
    lv.obj.del(lbl)
end)
