require("test_helpers")
print("--- test_obj ---")

test("obj.new creates object", function()
    local obj = lv.obj.new(window)
    expect_true(obj ~= nil, "obj should not be nil")
end)

test("obj.new without parent uses screen", function()
    local obj = lv.obj.new()
    expect_true(obj ~= nil)
    lv.obj.del(obj)
end)

test("obj.set_size and get_width/get_height", function()
    local obj = lv.obj.new(window)
    lv.obj.set_size(obj, 100, 50)
    test_tick(1)
    expect_eq(lv.obj.get_width(obj), 100, "width")
    expect_eq(lv.obj.get_height(obj), 50, "height")
    lv.obj.del(obj)
end)

test("obj.set_width / set_height separately", function()
    local obj = lv.obj.new(window)
    lv.obj.set_width(obj, 200)
    lv.obj.set_height(obj, 100)
    test_tick(1)
    expect_eq(lv.obj.get_width(obj), 200, "width")
    expect_eq(lv.obj.get_height(obj), 100, "height")
    lv.obj.del(obj)
end)

test("obj.set_pos and get_x", function()
    local obj = lv.obj.new(window)
    lv.obj.set_pos(obj, 10, 20)
    test_tick(1)
    expect_eq(lv.obj.get_x(obj), 10, "x")
    lv.obj.del(obj)
end)

test("obj.set_x / set_y", function()
    local obj = lv.obj.new(window)
    lv.obj.set_x(obj, 42)
    lv.obj.set_y(obj, 84)
    test_tick(1)
    expect_eq(lv.obj.get_x(obj), 42, "x")
    lv.obj.del(obj)
end)

test("obj.align center", function()
    local obj = lv.obj.new(window)
    lv.obj.set_size(obj, 50, 50)
    lv.obj.align(obj, lv.ALIGN_CENTER, 0, 0)
    test_tick(1)
    -- Should not crash, exact position depends on parent size
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.center shorthand", function()
    local obj = lv.obj.new(window)
    lv.obj.set_size(obj, 50, 50)
    lv.obj.center(obj)
    test_tick(1)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.add_flag / remove_flag", function()
    local obj = lv.obj.new(window)
    lv.obj.add_flag(obj, lv.OBJ_FLAG_HIDDEN)
    lv.obj.remove_flag(obj, lv.OBJ_FLAG_HIDDEN)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.clear_flag is alias for remove_flag", function()
    local obj = lv.obj.new(window)
    lv.obj.add_flag(obj, lv.OBJ_FLAG_HIDDEN)
    lv.obj.clear_flag(obj, lv.OBJ_FLAG_HIDDEN)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.add_state / clear_state / get_state", function()
    local obj = lv.obj.new(window)
    lv.obj.add_state(obj, lv.STATE_CHECKED)
    local st = lv.obj.get_state(obj)
    expect_true(st ~= 0, "state should include CHECKED")
    lv.obj.clear_state(obj, lv.STATE_CHECKED)
    lv.obj.del(obj)
end)

test("obj.set_flex_flow", function()
    local obj = lv.obj.new(window)
    lv.obj.set_flex_flow(obj, lv.FLEX_FLOW_COLUMN)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.set_flex_align", function()
    local obj = lv.obj.new(window)
    lv.obj.set_flex_flow(obj, lv.FLEX_FLOW_ROW)
    lv.obj.set_flex_align(obj, lv.FLEX_ALIGN_CENTER,
                          lv.FLEX_ALIGN_CENTER, lv.FLEX_ALIGN_CENTER)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.get_child / get_child_cnt", function()
    local parent = lv.obj.new(window)
    local c1 = lv.obj.new(parent)
    local c2 = lv.obj.new(parent)
    expect_eq(lv.obj.get_child_cnt(parent), 2, "child count")
    local first = lv.obj.get_child(parent, 0)
    expect_true(first ~= nil, "first child")
    lv.obj.del(parent)
end)

test("obj.get_child out of range returns nil", function()
    local parent = lv.obj.new(window)
    local child = lv.obj.get_child(parent, 99)
    expect_nil(child, "out-of-range child")
    lv.obj.del(parent)
end)

test("obj.add_style with style userdata", function()
    local obj = lv.obj.new(window)
    local s = lv.style.new()
    lv.style.set_bg_color(s, lv.color.hex(0xFF0000))
    lv.obj.add_style(obj, s)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.remove_style_all", function()
    local obj = lv.obj.new(window)
    local s = lv.style.new()
    lv.obj.add_style(obj, s)
    lv.obj.remove_style_all(obj)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj inline style setters (no selector)", function()
    local obj = lv.obj.new(window)
    lv.obj.set_style_bg_color(obj, lv.color.hex(0x112233))
    lv.obj.set_style_bg_opa(obj, lv.OPA_COVER)
    lv.obj.set_style_pad_row(obj, 5)
    lv.obj.set_style_pad_column(obj, 5)
    lv.obj.set_style_pad_top(obj, 10)
    lv.obj.set_style_pad_bottom(obj, 10)
    lv.obj.set_style_pad_left(obj, 10)
    lv.obj.set_style_translate_x(obj, 5)
    lv.obj.set_style_translate_y(obj, 5)
    lv.obj.set_style_radius(obj, 8)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj inline style setters (with selector)", function()
    local obj = lv.obj.new(window)
    lv.obj.set_style_bg_color(obj, lv.color.hex(0x112233), lv.PART_MAIN)
    lv.obj.set_style_pad_top(obj, 10, lv.PART_MAIN)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.set_style_text_color / text_font", function()
    local obj = lv.obj.new(window)
    lv.obj.set_style_text_color(obj, lv.color.white())
    lv.obj.set_style_text_font(obj, lv.font.nunito_bold_16)
    lv.obj.set_style_text_align(obj, lv.TEXT_ALIGN_CENTER)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.set_style_img_opa", function()
    local obj = lv.obj.new(window)
    lv.obj.set_style_img_opa(obj, lv.OPA_50)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.scroll_by / scroll_to / get_scroll_y", function()
    local obj = lv.obj.new(window)
    lv.obj.set_size(obj, 100, 100)
    lv.obj.scroll_to(obj, 0, 50, lv.ANIM_OFF)
    test_tick(1)
    local sy = lv.obj.get_scroll_y(obj)
    expect_type(sy, "number", "scroll_y type")
    lv.obj.del(obj)
end)

test("obj.set_scroll_snap_y / update_snap", function()
    local obj = lv.obj.new(window)
    lv.obj.set_scroll_snap_y(obj, lv.SCROLL_SNAP_CENTER)
    lv.obj.update_snap(obj, lv.ANIM_OFF)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.invalidate does not crash", function()
    local obj = lv.obj.new(window)
    lv.obj.invalidate(obj)
    expect_true(true)
    lv.obj.del(obj)
end)

test("obj.clean removes children", function()
    local parent = lv.obj.new(window)
    lv.obj.new(parent)
    lv.obj.new(parent)
    expect_eq(lv.obj.get_child_cnt(parent), 2, "before clean")
    lv.obj.clean(parent)
    expect_eq(lv.obj.get_child_cnt(parent), 0, "after clean")
    lv.obj.del(parent)
end)

test("obj.del does not crash", function()
    local obj = lv.obj.new(window)
    lv.obj.del(obj)
    expect_true(true)
end)

test("obj cache returns same userdata for same object", function()
    local obj = lv.obj.new(window)
    local c1 = lv.obj.get_child(window, lv.obj.get_child_cnt(window) - 1)
    -- c1 should be the same Lua userdata as obj
    expect_eq(obj, c1, "cache identity")
    lv.obj.del(obj)
end)

test("obj.get_coords", function()
    local obj = lv.obj.new(window)
    lv.obj.set_pos(obj, 10, 20)
    lv.obj.set_size(obj, 50, 30)
    test_tick(1)
    local area = lv.area.new()
    lv.obj.get_coords(obj, area)
    expect_type(lv.area.get_x1(area), "number", "x1 type")
    lv.obj.del(obj)
end)

test("obj.set_align", function()
    local obj = lv.obj.new(window)
    lv.obj.set_align(obj, lv.ALIGN_CENTER)
    expect_true(true)
    lv.obj.del(obj)
end)
