require("test_helpers")
print("--- test_style ---")

test("style.new creates style", function()
    local s = lv.style.new()
    expect_true(s ~= nil)
end)

test("style.reset", function()
    local s = lv.style.new()
    lv.style.set_bg_color(s, lv.color.hex(0xFF0000))
    lv.style.reset(s)
    expect_true(true)
end)

test("style background setters", function()
    local s = lv.style.new()
    lv.style.set_bg_color(s, lv.color.hex(0x112233))
    lv.style.set_bg_opa(s, lv.OPA_COVER)
    expect_true(true)
end)

test("style border setters", function()
    local s = lv.style.new()
    lv.style.set_border_width(s, 2)
    lv.style.set_border_color(s, lv.color.white())
    lv.style.set_border_opa(s, lv.OPA_50)
    lv.style.set_border_side(s, lv.BORDER_SIDE_BOTTOM)
    expect_true(true)
end)

test("style radius", function()
    local s = lv.style.new()
    lv.style.set_radius(s, 10)
    lv.style.set_radius(s, lv.RADIUS_CIRCLE)
    expect_true(true)
end)

test("style padding setters", function()
    local s = lv.style.new()
    lv.style.set_pad_all(s, 10)
    lv.style.set_pad_hor(s, 5)
    lv.style.set_pad_ver(s, 5)
    lv.style.set_pad_top(s, 1)
    lv.style.set_pad_bottom(s, 2)
    lv.style.set_pad_left(s, 3)
    lv.style.set_pad_right(s, 4)
    lv.style.set_pad_row(s, 8)
    lv.style.set_pad_column(s, 8)
    expect_true(true)
end)

test("style text setters", function()
    local s = lv.style.new()
    lv.style.set_text_color(s, lv.color.hex(0xFFFFFF))
    lv.style.set_text_opa(s, lv.OPA_COVER)
    lv.style.set_text_font(s, lv.font.nunito_bold_12)
    lv.style.set_text_align(s, lv.TEXT_ALIGN_CENTER)
    lv.style.set_text_line_space(s, 4)
    expect_true(true)
end)

test("style dimensions", function()
    local s = lv.style.new()
    lv.style.set_width(s, 100)
    lv.style.set_height(s, 50)
    expect_true(true)
end)

test("style arc", function()
    local s = lv.style.new()
    lv.style.set_arc_color(s, lv.color.hex(0x00FF00))
    lv.style.set_arc_width(s, 5)
    expect_true(true)
end)

test("style gradient", function()
    local s = lv.style.new()
    lv.style.set_bg_color(s, lv.color.hex(0x000000))
    lv.style.set_bg_grad_color(s, lv.color.hex(0xFFFFFF))
    lv.style.set_bg_grad_dir(s, lv.GRAD_DIR_VER)
    lv.style.set_bg_grad_stop(s, 200)
    lv.style.set_bg_main_stop(s, 0)
    lv.style.set_bg_dither_mode(s, lv.DITHER_ORDERED)
    expect_true(true)
end)

test("style image", function()
    local s = lv.style.new()
    lv.style.set_img_opa(s, lv.OPA_80)
    lv.style.set_img_recolor(s, lv.color.hex(0xFF0000))
    lv.style.set_img_recolor_opa(s, lv.OPA_50)
    expect_true(true)
end)

test("style translate", function()
    local s = lv.style.new()
    lv.style.set_translate_x(s, 10)
    lv.style.set_translate_y(s, -5)
    expect_true(true)
end)

test("style applied to obj", function()
    local s = lv.style.new()
    lv.style.set_bg_color(s, lv.color.hex(0xFF0000))
    lv.style.set_bg_opa(s, lv.OPA_COVER)
    lv.style.set_radius(s, 5)
    local obj = lv.obj.new(window)
    lv.obj.add_style(obj, s)
    test_tick(1)
    expect_true(true)
    lv.obj.del(obj)
end)
