require("test_helpers")
print("--- test_slider ---")

test("slider.new creates slider", function()
    local s = lv.slider.new(window)
    expect_true(s ~= nil)
    lv.obj.del(s)
end)

test("slider.set_range / set_value / get_value", function()
    local s = lv.slider.new(window)
    lv.slider.set_range(s, 0, 100)
    lv.slider.set_value(s, 42, lv.ANIM_OFF)
    expect_eq(lv.slider.get_value(s), 42, "value")
    lv.obj.del(s)
end)

test("slider.set_value with animation", function()
    local s = lv.slider.new(window)
    lv.slider.set_range(s, 0, 100)
    lv.slider.set_value(s, 75, lv.ANIM_ON)
    expect_true(true)
    lv.obj.del(s)
end)

test("slider.set_value clamped to range", function()
    local s = lv.slider.new(window)
    lv.slider.set_range(s, 10, 50)
    lv.slider.set_value(s, 999, lv.ANIM_OFF)
    expect_eq(lv.slider.get_value(s), 50, "clamped max")
    lv.slider.set_value(s, -100, lv.ANIM_OFF)
    expect_eq(lv.slider.get_value(s), 10, "clamped min")
    lv.obj.del(s)
end)
