require("test_helpers")
print("--- test_anim ---")

test("anim.new creates animation", function()
    local a = lv.anim.new()
    expect_true(a ~= nil)
end)

test("anim basic setup", function()
    local a = lv.anim.new()
    local obj = lv.obj.new(window)
    lv.anim.set_var(a, obj)
    lv.anim.set_values(a, 0, 100)
    lv.anim.set_time(a, 500)
    expect_true(true)
    lv.obj.del(obj)
end)

test("anim.set_duration is alias for set_time", function()
    local a = lv.anim.new()
    lv.anim.set_duration(a, 300)
    expect_true(true)
end)

test("anim.set_exec_cb", function()
    local a = lv.anim.new()
    local obj = lv.obj.new(window)
    local values = {}
    lv.anim.set_var(a, obj)
    lv.anim.set_values(a, 0, 10)
    lv.anim.set_time(a, 100)
    lv.anim.set_exec_cb(a, function(o, val)
        table.insert(values, val)
    end)
    lv.anim.start(a)
    test_tick(20)
    expect_true(#values > 0, "exec_cb should be called")
    lv.obj.del(obj)
end)

test("anim.set_path_cb", function()
    local a = lv.anim.new()
    lv.anim.set_path_cb(a, lv.anim.path_ease_in_out)
    lv.anim.set_path_cb(a, lv.anim.path_linear)
    lv.anim.set_path_cb(a, lv.anim.path_ease_out)
    lv.anim.set_path_cb(a, lv.anim.path_ease_in)
    lv.anim.set_path_cb(a, lv.anim.path_overshoot)
    lv.anim.set_path_cb(a, lv.anim.path_bounce)
    expect_true(true)
end)

test("anim.set_delay", function()
    local a = lv.anim.new()
    lv.anim.set_delay(a, 200)
    expect_true(true)
end)

test("anim.set_early_apply", function()
    local a = lv.anim.new()
    lv.anim.set_early_apply(a, true)
    lv.anim.set_early_apply(a, false)
    expect_true(true)
end)

test("anim.set_playback_time", function()
    local a = lv.anim.new()
    lv.anim.set_playback_time(a, 200)
    expect_true(true)
end)

test("anim.set_repeat_count", function()
    local a = lv.anim.new()
    lv.anim.set_repeat_count(a, 3)
    lv.anim.set_repeat_count(a, lv.ANIM_REPEAT_INFINITE)
    expect_true(true)
end)

test("anim full lifecycle", function()
    local obj = lv.obj.new(window)
    lv.obj.set_size(obj, 50, 50)
    lv.obj.set_pos(obj, 0, 0)

    local a = lv.anim.new()
    lv.anim.set_var(a, obj)
    lv.anim.set_values(a, 0, 100)
    lv.anim.set_time(a, 100)
    lv.anim.set_path_cb(a, lv.anim.path_linear)
    lv.anim.set_exec_cb(a, function(o, val)
        lv.obj.set_x(o, val)
    end)
    lv.anim.start(a)
    test_tick(30)
    -- Object x should have moved
    expect_true(true)
    lv.obj.del(obj)
end)

test("anim_var.del", function()
    local obj = lv.obj.new(window)
    local a = lv.anim.new()
    lv.anim.set_var(a, obj)
    lv.anim.set_values(a, 0, 100)
    lv.anim.set_time(a, 1000)
    lv.anim.set_exec_cb(a, function(o, v) end)
    lv.anim.start(a)
    -- Delete animation by var
    lv.anim_var.del(a)
    expect_true(true)
    lv.obj.del(obj)
end)
